from PIL import Image
import os
from pathlib import Path
from collections import defaultdict


def load_images_and_colors(image_folder):
    """Load all PNG images and extract their unique colors."""
    image_colors = {}

    png_files = sorted(Path(image_folder).glob("*.png"))

    for image_path in png_files:
        try:
            img = Image.open(image_path).convert('RGB')
            colors = set(img.getdata())
            image_colors[image_path.name] = colors
            print(f"OK  {image_path.name:25} ({img.size[0]:3}x{img.size[1]:3}) - {len(colors):4} colors")
        except Exception as e:
            print(f"ERR {image_path.name}: {e}")

    return image_colors


def find_distinct_colors(image_colors):
    """Find colors that appear in one image but not in any other."""
    distinct_colors = defaultdict(set)

    for image_name, colors in image_colors.items():
        other_colors = set()
        for other_name, other_color_set in image_colors.items():
            if other_name != image_name:
                other_colors.update(other_color_set)
        distinct_colors[image_name] = colors - other_colors

    return distinct_colors


def export_to_python(image_colors, distinct_colors,
                     filename="distinct_colors_dict.py"):
    """Write DISTINCT_COLORS dict to a Python file."""
    with open(filename, 'w', encoding='utf-8') as f:
        f.write("# Distinct colors for each hazard symbol\n")
        f.write("# Auto-generated by analyze_colors.py\n")
        f.write("DISTINCT_COLORS = {\n")

        for image_name in sorted(image_colors.keys()):
            clean_name = image_name.replace('.png', '')
            colors_list = sorted(list(distinct_colors[image_name]))
            f.write(f"    '{clean_name}': [\n")
            for rgb in colors_list:
                f.write(f"        {rgb},\n")
            f.write("    ],\n")

        f.write("}\n")

    total = sum(len(v) for v in distinct_colors.values())
    print(f"\nWrote {total} distinct colors across "
          f"{len(image_colors)} images to '{filename}'")


def main():
    """Main entry point."""
    image_folder = "hazards symbols"

    if not os.path.exists(image_folder):
        print(f"Error: Folder '{image_folder}' not found!")
        print("Make sure the 'hazards symbols' folder is in the same")
        print("directory as this script.")
        return

    print(f"Loading images from '{image_folder}'...\n")
    image_colors = load_images_and_colors(image_folder)

    if not image_colors:
        print("No PNG images found.")
        return

    print(f"\nFinding distinct colors...")
    distinct_colors = find_distinct_colors(image_colors)

    for name in sorted(image_colors.keys()):
        clean = name.replace('.png', '')
        n = len(distinct_colors[name])
        print(f"  {clean:20}: {n:3} distinct colors")

    export_to_python(image_colors, distinct_colors)


if __name__ == "__main__":
    main()